drivers: video: remove unused variable 'mdnie_mode'
../../../../../../kernel/samsung/exynos990/drivers/video/fbdev/exynos/panel/mdnie.c:893:6: error: unused variable 'mdnie_mode' [-Werror,-Wunused-variable]
        int mdnie_mode = mdnie_current_state(mdnie);
            ^